services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile    
    container_name: api_container
    expose:
      - "8000"
    networks:
      - backend
    env_file:
      - .env
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media

  nginx:
    image: nginx:latest
    container_name: nginx_container
    depends_on:
      - api
    ports:
      - "80:80"
    networks:
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/app/staticfiles
      - media_volume:/app/media

networks:
  backend:

volumes:
  static_volume:
  media_volume:
